// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {opgg} from '../models';

export function SetRune(arg1:opgg.Rune):Promise<void>;
