// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentSummoner() {
  return window['go']['api']['Api']['CurrentSummoner']();
}

export function GameLauncher() {
  return window['go']['api']['Api']['GameLauncher']();
}

export function GetConfig() {
  return window['go']['api']['Api']['GetConfig']();
}

export function GetGameInfo(arg1) {
  return window['go']['api']['Api']['GetGameInfo'](arg1);
}

export function GetRankInfo(arg1) {
  return window['go']['api']['Api']['GetRankInfo'](arg1);
}

export function GetState() {
  return window['go']['api']['Api']['GetState']();
}

export function GetSummoner(arg1) {
  return window['go']['api']['Api']['GetSummoner'](arg1);
}

export function ListGameSummary(arg1, arg2, arg3) {
  return window['go']['api']['Api']['ListGameSummary'](arg1, arg2, arg3);
}

export function SearchSummoner(arg1) {
  return window['go']['api']['Api']['SearchSummoner'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['api']['Api']['SetConfig'](arg1);
}

export function SetRune(arg1) {
  return window['go']['api']['Api']['SetRune'](arg1);
}

export function TierMeta() {
  return window['go']['api']['Api']['TierMeta']();
}
