// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GameLauncher() {
  return window['go']['api']['Api']['GameLauncher']();
}

export function GetState() {
  return window['go']['api']['Api']['GetState']();
}

export function SetRune(arg1) {
  return window['go']['api']['Api']['SetRune'](arg1);
}
